version: '3.4'

services:

  bot:
    image: onemillionquacks
    restart: on-failure:3
    build: .
    env_file:
      - .env
    depends_on:
      - db

  db:
    restart: always
    image: redis
    volumes:
      - db-data:/data
  
  backup:
    image: pants1/docker-volume-backup:latest
    env_file:
     - .env.backup
    depends_on:
     - db

volumes:
  # Database persistence
  db-data: